---
title: "Sequencing technology comparison"
output: html_document
---




```{r, message=FALSE,echo=TRUE}
library("MicrobiotaProcess")
library("ggpubr")
library("ape")
library("VennDiagram")
library("UpSetR")
library("vegan")

WorkingPS<-readRDS("Processed_data/WorkingPS.rds")
```


```{r}
WorkingPS_glom <- get_taxadf(WorkingPS, 
                     taxlevel=7,
                     type = "species")

WorkingPS_glom_tree = rtree(ntaxa(WorkingPS_glom), 
                    rooted=TRUE, 
                    tip.label=taxa_names(WorkingPS_glom))


WorkingPS_glom2 <- phyloseq(phyloseq::tax_table(WorkingPS_glom),
                            phyloseq::otu_table(WorkingPS_glom),
                            WorkingPS_glom_tree,
                            phyloseq::sample_data(WorkingPS_glom))

```

PcoA 
----

```{r, message=FALSE,echo=TRUE}

pcoa_results <- get_pcoa(obj=WorkingPS_glom2, 
                      distmethod="wunifrac", 
                      method="hellinger")


pcoaplot1 <- ggordpoint(obj=pcoa_results,
                          pc=c(1, 2),
                          biplot=FALSE,
                          factorNames=c("seq_tech", "Region"), 
                          ellipse=TRUE,
                          poinsize = 1.8,
                          stroke = 0.2)+
  theme(legend.box = "horizontal", legend.position = "right")+
  scale_fill_brewer(palette ="Set2")+
  theme(legend.text=element_text(size=8))+
  theme(legend.title = element_blank())+ 
  theme(plot.title = element_blank())+
  theme(legend.direction = "vertical", legend.box = "vertical")+
  guides(fill = guide_legend(keywidth = 0.6, 
                             keyheight = 0.7,
                             ncol = 1));pcoaplot1

```


Upset Plot 
----

```{r}
upsetda <- get_upset(obj=WorkingPS_glom2, factorNames="seq_tech")

upset(upsetda, sets=unique(as.vector(sample_data(WorkingPS_glom2)$seq_tech)), 
      sets.bar.color = "#56B4E9",
      order.by = "freq", 
      empty.intersections = "on")

```

Permanova
---- 

```{r}
dist_mat <- get_dist(WorkingPS_glom2, distmethod ="wunifrac", method="hellinger")
sampleda <- data.frame(sample_data(WorkingPS_glom2), check.names=FALSE)
sampleda <- sampleda[match(colnames(as.matrix(dist_mat)),rownames(sampleda)),,drop=FALSE]
sampleda$seq_tech <- factor(sampleda$seq_tech)
set.seed(1024)
adonis_res <- adonis(dist_mat ~ seq_tech*Week, data=sampleda, permutation=9999)
data.frame(adonis_res$aov.tab)

```

